export const tagTypes = {
  // favourite: 'favourite',
  // prescription: 'prescription',
  // patient: 'patient',
  // appointments: 'appointments',
  // appointmentsTimes: 'appointmentsTimes',
  // doctor: 'doctor',
  // reviews: 'reviews',
  // timeSlot: 'timeSlot',
  // blogs: 'blogs',
  // medicine: 'medicine',
  // comment:'comment',
  // clinic: 'clinic',
  // overview:'overview',
  // staff: 'staff',
  member: "member",
  profile: "profile",
  details: "details",
  network: "network",
  email: "email",
};

export const tagTypeList = [
  // tagTypes.favourite,
  // tagTypes.prescription,
  // tagTypes.patient,
  // tagTypes.appointments,
  // tagTypes.appointmentsTimes,
  // tagTypes.doctor,
  // tagTypes.reviews,
  // tagTypes.timeSlot,
  // tagTypes.blogs,
  // tagTypes.comment,
  // tagTypes.medicine,
  // tagTypes.overview,
  // tagTypes.staff,

  tagTypes.profile,
  tagTypes.member,
  tagTypes.details,
  tagTypes.network,
  tagTypes.email,
];
