export const tagTypes = {
  member: "member",
  profile: "profile",
  details: "details",
  network: "network",
  email: "email",
  post: "post",
  verification: "verification",
  chat: "chat",
  messages: "messages",
  chatrequest: "chatrequest",
  news: "news",
  explore: "explore",
  poll: "poll",
  rating: "rating",
  promotion: "promotion",
  opinion: "opinion",
  story: "story",
  search: 'search',
  like: "like",
  comment: "comment",
  notification: "notification",
};

export const tagTypeList = [
  tagTypes.profile,
  tagTypes.member,
  tagTypes.details,
  tagTypes.network,
  tagTypes.email,
  tagTypes.post,
  tagTypes.verification,
  tagTypes.chat,
  tagTypes.messages,
  tagTypes.chatrequest,
  tagTypes.news,
  tagTypes.explore,
  tagTypes.poll,
  tagTypes.rating,
  tagTypes.promotion,
  tagTypes.opinion,
  tagTypes.story,
  tagTypes.search,
  tagTypes.like,
  tagTypes.comment,
  tagTypes.notification,
  // Add more tag types as needed
];
